# Generated by Django 4.0.4 on 2022-05-19 13:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0003_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Contact',
            new_name='Home_contact',
        ),
    ]
