# Generated by Django 4.0.4 on 2022-05-19 13:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0004_rename_contact_home_contact'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Home_contact',
            new_name='Contact',
        ),
    ]
